#### 1. Import the numpy package under the name `np` (★☆☆)
#### 4. Create a null vector of size 10 (★☆☆)

In [1]:
import numpy as np
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1

In [2]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.Create a vector with values ranging from 10 to 49 (★☆☆)

In [3]:
arr_3 = np.arange(10,50)
print(arr_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Reverse a vector (first element becomes last) (★☆☆)

In [5]:
arr_3 = np.arange(10,50)
print(arr_3[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
arr_4 = np.arange(9).reshape(3,3)
print(arr_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [16]:
# arr_5 = [1,2,0,0,4,0]
# arr_6 = np.nonzero(arr_5)
# print(arr_6)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 6. Create a 3x3 identity matrix

In [17]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 7. Create a 3x3x3 array with random values

In [20]:
x = np.random.random((3,3,3))
print(x)

[[[0.11578522 0.89036699 0.29411133]
  [0.29462646 0.64958336 0.34893985]
  [0.86395779 0.15363197 0.92150439]]

 [[0.9799244  0.37459126 0.55565635]
  [0.5023169  0.90377454 0.116026  ]
  [0.62218473 0.29361255 0.73798592]]

 [[0.56869674 0.6605981  0.79881371]
  [0.27068579 0.1379734  0.53671725]
  [0.65267154 0.01685627 0.01431786]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [25]:
y = np.random.random((10,10))
ymin = y.min
ymax = y.max
ymin,ymax = y.min(),y.max()
print(ymin,ymax)


0.0021670034530556492 0.9752473867082467
